import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  mainWrapper: {
    height: "75%",
    flexDirection: "row",
    backgroundColor: "gray",
  },

  santeWrapper: {
    height: "92%",
    flexDirection: "row",
    backgroundColor: "gray",
  },
  santeMobileWrapper: {
    height: "85%",
    flexDirection: "row",
    backgroundColor: "gray",
  },
  itemListWrapper: {
    flex: 1.8,
    backgroundColor: "#222121",
  },
  mobileItemListWrapper: {
    flex: 1,
    backgroundColor: "#222121",
  },
  cartWrapper: {
    flex: 1.5,
    backgroundColor: "#BBBBBB",
    marginBottom: 10,
  },

  item: {
    width: "22%",
    backgroundColor: "#f6f7fb",
    height: 80,
    margin: 8,
    borderRadius: 10,
    justifyContent: "center",
  },
  mobileItem: {
    width: "40%",
    backgroundColor: "#f6f7fb",
    height: 50,
    margin: 8,
    borderRadius: 10,
    justifyContent: "center",
  },
  categoryItem: {
    width: "16%",
    backgroundColor: "#56A2C8",
    height: 50,
    margin: 4,
    borderRadius: 10,
    justifyContent: "center",
  },
  mobileCategoryItem: {
    width: 100,
    backgroundColor: "#56A2C8",
    height: 40,
    margin: 4,
    borderRadius: 10,
    justifyContent: "center",
  },
  categorySelectedItem: {
    width: "16%",
    backgroundColor: "#005e9e",
    height: 50,
    margin: 4,
    borderRadius: 10,
    justifyContent: "center",
  },
  mobileCategorySelectedItem: {
    width: 100,
    backgroundColor: "#005e9e",
    height: 40,
    margin: 4,
    borderRadius: 10,
    justifyContent: "center",
  },
  categoryTitle: {
    color: "white",

    textAlign: "center",
    fontWeight: "600",
    fontSize: 12,
  },
  title: {
    color: "black",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "600",
  },
  mobileTitle: {
    color: "black",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  cartTableHead: {
    flexDirection: "row",
    backgroundColor: "#222121",
  },
  tableHead: {
    width: "24%",
    color: "white",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "600",
    padding: 10,
  },
  mobileTableHead: {
    width: "24%",
    color: "white",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",
    padding: 10,
  },
  cartItem: {
    backgroundColor: "#FFF",
    flexDirection: "row",
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomColor: "#000",
    borderBottomWidth: 1,
  },
  cartMobileItem: {
    backgroundColor: "#FFF",
    flexDirection: "row",
    paddingTop: 5,
  },
  cartItemText: {
    width: "24%",
    color: "black",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  mobilecartItemText: {
    width: "24%",
    color: "black",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",
  },
  totalTxt: {
    width: "20%",
    color: "black",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  qtyRow: {
    width: "25%",
    flexDirection: "row",

    justifyContent: "space-around",
  },
  qtyText: {
    color: "black",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "600",
  },
  qtyInput: {
    color: "black",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "600",

    marginTop: -10,
  },
  qtyMobileInput: {
    color: "black",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",

    marginTop: -10,
  },
  hold: {
    backgroundColor: "#eaebeb",

    width: "18%",
    height: 50,
    borderRadius: 10,
    marginRight: 5,
    marginLeft: 5,
    justifyContent: "center",
  },
  clear: {
    width: "30%",
    backgroundColor: "#D30B0B",
    borderRadius: 10,
    justifyContent: "center",
  },
  bill: {
    width: "18%",
    backgroundColor: "#14C107",
    borderRadius: 10,
    marginRight: 5,
    marginLeft: 5,
    justifyContent: "center",
  },
  btnText: {
    color: "#7d7e7a",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "600",
  },
  mobilebtnText: {
    color: "#7d7e7a",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",
  },
  optionBtn: {
    flexDirection: "row",
    width: "85%",
    backgroundColor: "#56A2C8",
    borderRadius: 5,
    padding: 10,
    flex: 1,
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  selectedOpt: {
    flexDirection: "row",
    width: "85%",
    backgroundColor: "#005e9e",
    borderRadius: 5,
    padding: 10,
    flex: 1,
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },

  santeSelected: {
    flexDirection: "row",
    backgroundColor: "#005e9e",
    width: "85%",
    borderRadius: 5,
    padding: 10,
    flex: 1,
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  paymentOptions: {
    margin: 5,
    backgroundColor: "#f6f7fb",
    borderRadius: 10,
    justifyContent: "center",
    // width: 90,
    height: 50,
  },
  paymentMobileOptions: {
    margin: 5,
    backgroundColor: "#f6f7fb",
    borderRadius: 10,
    justifyContent: "center",
    // width: 90,
    height: 30,
  },
  container: {
    flexDirection: "row",
    alignItems: "center",
    alignContent: "space-between",
    justifyContent: "space-around",
  },
  selectedpayment: {
    margin: 5,
    backgroundColor: "#005e9e",
    borderRadius: 10,
    justifyContent: "center",
    // width: 90,
    height: 50,
  },
  selectedMobilepayment: {
    margin: 5,
    backgroundColor: "#005e9e",
    borderRadius: 10,
    justifyContent: "center",
    // width: 90,
    height: 30,
  },
  selectedBtnTxt: {
    color: "white",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "600",
  },
  mobileselectedBtnTxt: {
    color: "white",
    fontSize: 14,
    textAlign: "center",
    fontWeight: "600",
  },
});
